### ISSUE TITLE
Regression: NullReferenceException thrown when argument customization is not provided.

### ISSUE THREAD

**Issue by Romanx** [Romanx/Cake.Coverlet#6]
Seems to surface like #3 although could be something different.

**Comment by anthony-roe-cko** [comment]
Hi the stacktrace is below:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Cake.Coverlet.CoverletAliases.<>c__DisplayClass0_0.<DotNetCoreTest>b__0(ProcessArgumentBuilder args)
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Common.Tools.DotNetCore.Test.DotNetCoreTester.Test(String project, DotNetCoreTestSettings settings)
   at Submission#0.DotNetCoreTest(FilePath project, DotNetCoreTestSettings settings, CoverletSettings coverletSettings)
   at Submission#0.<<Initialize>>b__0_2()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass20_0.<Does>b__0(ICakeContext x)
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__30.MoveNext()`

**Comment by ctcoulter** [comment]
I haven't had a chance to pull it down and check and am not at a computer, but at first glance it looks like the null check needs to happen in `ProcessArguments` as well before trying to use the builder.

**Comment by Romanx** [comment]
Hi there,

Took me awhile to get to the bottom of this. It seems while making the change for #5 I managed to somehow get a tag on a version of code that doesn't exist but got pushed remote and overwritten after a bad merge. This code got pushed to nuget and only had half of my actual changes. The odd phantom commit can be found [here.](https://github.com/Romanx/Cake.Coverlet/commit/116ab2f94abfe0e44226c3add88dda2687635750)

Since i use git versioning to determine my scheme i've bumped the version to 1.3 to make sure people should pull the new version however it has no actual new changes but should fix this regression.

Hopefully that makes some sense, please report back if you have any issues or just to confirm it's fixed.

Thanks,

**Comment by anthony-roe-cko** [comment]
All seems good now @Romanx  thanks for the very quick fix 👍

**Comment by Romanx** [comment]
You're more than welcome, thanks for the report.
